### ISSUE TITLE
Suggestion - create and signpost a community area for people to say what are working on / want to work on.

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/Crescendo#145]
On my computer I have docker, git, and terraform all of which are candidates for crescendo modules.
If they are already being worked on I'd be happy to contribute - but how do I find the person/people working on them?  If they're not , and I'm the first to start, how do potential contributors find me?     
And if I think I'm the first to do git, and say "I'm working on a crescendo module for git"  someone can step in and say "Mate, it's been done they called it 'LoudGit' " I can check out what I hadn't found and save myself a lot of time 

Alternatively two or more of us start work, we duplicate effort and produce overlapping subsets of functionality. Whoever publishes first becomes the go-to module for that even if theirs isn't the best implementation.  Anything valuable enough to be worth doing, has probably got more than one person looking at it, so the "smart" thing is just to wait for someone else to produce what you want - but if everyone is "smart" no-one will do anything.

**Comment by theJasonHelmick** [comment]
Thanks for the suggestion @jhoneill. This is a great opportunity for the community to share information about working with Crescendo.  A couple of things that might be helpful:

1. By default, Crescendo tags an exported module so that its easy to find on the PowerShell Gallery. Type Crescendo in the search bar and you will get a list of all the modules wrapped by Crescendo that has been published.  I believe there are 4 currently published. I am aware of a couple of modules where the author has chosen not to publish to the gallery, but its a good place to start.
2. The Crescendo repository now contains a category for discussion "Community Crescendo wrapped commands". This might be a good starting place where folks can discuss the commands they are getting started on, share json configurations, and help others. https://github.com/PowerShell/Crescendo/discussions/categories/crescendo-wrapped-commands

I'm always  open to additional ideas on how to best support folks developing Crescendo wrapped commands including supporting the community in other locations and forums.
