### ISSUE TITLE
Invoke-WindowsNativeAppWithElevation is it actual elevation?

### ISSUE THREAD

**Issue by jborean93** [PowerShell/Crescendo#81]
I was looking over the release notes for preview 2 and it mentions it has support for elevating a command on Windows. Looking at the code it seems like this is done through [Invoke-WindowsNativeAppWithElevation](https://github.com/PowerShell/Crescendo/blob/29b3b64e5b2ce64a1f72405f7a5420b160fa9dbb/Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1#L750). Essentially it calls `Start-Process -FilePath cmd.exe -ArgumentList @('/c, '/d', $pwd, 'command to run') -Credential $cred`. If you have UAC enabled on your host or you are targeting a user that is not the builtin Administrator account the new process won't actually be elevated. This is because `Start-Process ... -Credential` relies on `[CreateProcessWithLogonW](https://github.com/PowerShell/PowerShell/blob/32a38fcac33e5f93270f86a15ca7f93e509091f9/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2484-L2533) which essentially creates an interactive token for the specified user and starts the process with that new token.

The interactive token retrieved in this call is only elevated if

* UAC is disabled
* The target account is the builtin administrator and [UAC Admin Approval Mode for the Builtin-in Administrator Account](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-admin-approval-mode-for-the-built-in-administrator-account) is not enabled
  * The builtin admin account is the SID ending with `S-1-5-21-{domain sid}-500`
  * This is not enabled by default

While you could argue it "elevates" the token from a network to interactive logon which the former is a bit tricky with some APIs this isn't really the case because `Start-Process ... -Credential` fails on a network logon like WinRM due to the station not being set up properly beforehand.

Ultimately the only true way to elevate a process is by using `-Verb RunAs` and accept the UAC prompt. From an automation perspective this is not possible because you can't automatically accept this prompt so the usability is limited on Windows at best.

It's also questionable why you call `cmd.exe /c ...` in the `Start-Process` call. Why not just invoke the executable directly, by bringing cmd into the picture you now add another layer of complication and quote escaping rules people need to consider.

**Comment by ethanbergstrom** [comment]
Thanks for doing that research, @jborean93.

I was looking to add the Elevation block to my Chocolatey wrapper in the hopes it would trigger a UAC prompt for users who didn't have their terminal already elevated, but it seems like this enhancement wont actually solve for that.

**Comment by theJasonHelmick** [comment]
@jborean93 - Thank you for detailed breakdown.  you are correct, we are essentially using `Start-Process` under the covers as you describe.  We aren't adding new features to Windows, instead using the ones that exist.  This may not work in all scenarios, such as UAC.  Crescendo is extendable, so you could use your own elevation for scenarios outside of `Invoke-WindowsNativeAppWithElevation`.  @JamesWTruher may also wish to respond.  @sdwheeler for doc purposes.

**Comment by JamesWTruher** [comment]
@jborean93 - As I was coding this up I had similar concerns, Windows does make solutions for elevation, ahem, _problematic_. I found a couple of different paths I could run. I thought about invoking RunAs.Exe directly, I found this tool [https://github.com/gerardog/gsudo](gsudo) which was interesting, but at the end of the day I thought that I would provide something that could perhaps be used as scaffolding rather than nothing. These previews allow folks to kick the tires a bit while we build and this is one of the things which _really_ needs kicking.

I _think_ the configuration is flexible enough for folks to create their own solutions as well, and my provided solution is just one approach. One of the reasons I provided it was to hopefully illuminate some of the problems with this on Windows (capturing output/error is not obvious if you're used to a UNIX system). If you think this function has merit, we can leave it in. I do like the idea of adding support for the `-verb runas`, which would be trivial to add. Of course, I would totally like other suggestions on how to do this other than "please, let it do magic".
